### ISSUE TITLE
Add "skip ahead 15 seconds" to lock screen player.

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/DEV-ios#215]
Here is the Spotify podcast context:

![Image from iOS (1)](https://user-images.githubusercontent.com/3102842/76247515-0e7b8500-6216-11ea-9c4c-180c39dccfbc.png)

Ours does not have the "skip ahead/back" buttons and I think it should, eh:

![Image from iOS](https://user-images.githubusercontent.com/3102842/76247527-13d8cf80-6216-11ea-98c9-849d6d61e542.png)

**Comment by benhalpern** [comment]
It also occurs to me that we should send the podcast image to this context too, instead of the app image.

**Comment by benhalpern** [comment]
@fdoxyz I was curious about this so I gave it a whirl. Not sure if perfect implementation but I think it works. #217

**Comment by fdoxyz** [comment]
Sharing some small comments on the PR soon but it's looking great!

As for the Album art: I gave it some thought at first and for the first implementation (released in `1.4.0`) I did considered it out of scope in order to get the feature out the door. Just created an issue to track/discuss this in particular.
