### ISSUE TITLE
broken external website link in profile

### ISSUE THREAD

**Issue by gokatz** [thepracticaldev/DEV-ios#55]
Thanks for this, @benhalpern! It should be fun using the iOS app 🍾. Just curious to know, if we used our web assets to embed in the ios app. If so, is there any ideas for a standalone PWAs?

**Description**
Website link provided inside the user profile is not working. When clicking the external link icon, we are not navigating to the actual website.

**To Reproduce**
1. Go to User profile
2. Click on external link icon

**Screenshots**
![dev](https://user-images.githubusercontent.com/15158776/47476104-65103b00-d83c-11e8-8ced-f0322efbbcb5.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone 6s
 - OS V: iOS 12.0.1

**Comment by benhalpern** [comment]
Yeah, external links seem to be occasionally causing issues. Haven't pinned it down yet.

In general I think it makes sense to open up all external links in a popup window. This _may_ be less trivial because we do page fetches via JS, but I think we should be able to intercept page change attempts in the app and launch external links.

This would be the same as intercepting, say, a link to `/notifications` and shooting you to that tab instead of opening it in the current view.

**Comment by benhalpern** [comment]
Closing because out of date
